
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - "Type: Dependency"
  - package-ecosystem: 'npm'
    directory: '/example'
    schedule:
      interval: 'weekly'
    labels:
      - "Type: Dependency"