git:
  submodules: false

jobs:
  include:
  # unit test
  - language: node_js
    node_js: 10
    os: linux
    dist: trusty
    cache:
      yarn: true
      directories:
        - node_modules
        - example/node_modules
    install:
      - yarn --frozen-lockfile
    script:
      - yarn lint && yarn test && yarn build
      - cd example && yarn --frozen-lockfile && yarn lint && yarn test --ci
  # build check
  - language: android
    jdk: oraclejdk8
    os: linux
    dist: trusty
    before_cache:
      - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
      - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    before_install:
      - yes | sdkmanager "build-tools;29.0.2"
    cache:
      yarn: true
      directories:
        - node_modules
        - example/node_modules
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $HOME/.android/build-cache
    android:
      components:
        - tools
        - platform-tools
        - android-29
        - extra-google-m2repository
        - extra-android-m2repository
        - extra-google-google_play_services
    install:
      - nvm install 10
      - curl -o- -L https://yarnpkg.com/install.sh | bash
      - export PATH="$HOME/.yarn/bin:$PATH"
      - yarn --frozen-lockfile && yarn build
      - cd example
      - yarn --frozen-lockfile
    script:
      - cd android
      - ./gradlew clean build
  # e2e test
  - language: objective-c
    os: osx
    osx_image: xcode11.5
    podfile: example/ios/Podfile
    cache:
      yarn: true
      cocoapods: true
      directories:
        - node_modules
        - example/node_modules
    before_install:
      - nvm install 10
      - curl -o- -L https://yarnpkg.com/install.sh | bash
      - export PATH="$HOME/.yarn/bin:$PATH"
      - yarn --frozen-lockfile && yarn build
      - cd example
      - yarn --frozen-lockfile
      - cd ios
      - pod install
      - cd ..
    install:
      - brew tap wix/brew
      - brew install applesimutils
      - npm i -g npm
      - npm i -g react-native-cli
      - npm i -g detox-cli
    script:
      - detox build --configuration ios.sim.release
      - detox test --configuration ios.sim.release --cleanup