git:
  submodules: false

matrix:
  include:
  # unit test
  - language: node_js
    node_js: 10
    script:
      - yarn install && yarn lint && yarn test && yarn build
      - cd example && yarn install && yarn lint && yarn test --ci --updateSnapshot
  # build check
  - language: android
    sudo: false
    jdk: oraclejdk8
    os: linux
    licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
    before_cache:
      - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
      - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
        - $HOME/.yarn-cache
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $HOME/.android/build-cache
    android:
      components:
        - tools
        - platform-tools
        - build-tools-28.0.3
        - android-28
        - extra-google-m2repository
        - extra-android-m2repository
        - extra-google-google_play_services
    install:
      - nvm install 10
      - curl -o- -L https://yarnpkg.com/install.sh | bash
      - export PATH="$HOME/.yarn/bin:$PATH"
      - yarn install && yarn build
      - cd example
      - yarn install
    script:
      - cd android
      - ./gradlew clean build
  # e2e test
  - language: objective-c
    os: osx
    osx_image: xcode11.4
    cache:
      directories:
      - $HOME/.yarn-cache
    before_install:
      - nvm install 10
      - curl -o- -L https://yarnpkg.com/install.sh | bash
      - export PATH="$HOME/.yarn/bin:$PATH"
      - yarn install && yarn build
      - cd example
      - yarn install
      - cd ios
      - pod install
      - cd ..
    install:
      - brew tap wix/brew
      - brew install applesimutils
      - npm install -g react-native-cli
      - npm install -g detox-cli
    script:
      - detox build --configuration ios.sim.release -l verbose
      - detox test --configuration ios.sim.release --cleanup -l verbose