matrix:
  include:
  - language: node_js
    node_js: 8
    script:
    - yarn && yarn lint && yarn test
    - cd example && yarn && yarn lint && cd ..
  - language: android
    sudo: false
    jdk: oraclejdk8
    os: linux
    before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
      - $HOME/.yarn-cache
      - $HOME/.gradle/caches/
      - $HOME/.gradle/wrapper/
      - $HOME/.android/build-cache
    android:
      components:
      - tools
      - platform-tools
      - android-28
      - extra-google-m2repository
      - extra-android-m2repository
      - extra-google-google_play_services
    install:
    - nvm install 8
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"
    - cd example
    - yarn
    script:
    - cd android
    - "./gradlew clean build"
  - language: objective-c
    os: osx
    osx_image: xcode11.3
    node_js: 8
    cache:
      directories:
      - "$HOME/.yarn-cache"
    before_install:
    - nvm install 8
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"
    - cd example
    - yarn
    - cd ios
    script:
    - xcodebuild -workspace example.xcworkspace -configuration Debug
      -scheme example -destination 'platform=iOS Simulator,OS=12.2,name=iPhone X'
      -derivedDataPath build/example