name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  USER_NODE_VERSION: 20
  USER_JAVA_VERSION: 17
  IOS_SIMULATOR_DEVICE: iPhone 15 Pro
  IOS_SIMULATOR_RUNTIME: iOS-17-5

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.USER_NODE_VERSION }}
          cache: 'yarn'
      - run: make dependencies
      - run: make check
      - run: make dependencies-example
      - run: make check-example

  build-android:
    runs-on: macos-14
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.USER_NODE_VERSION }}
          cache: 'yarn'
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.USER_JAVA_VERSION }}
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v3
      - run: yarn global add react-native-cli
      - run: yarn global add detox-cli
      - run: make dependencies
      - run: make dependencies-example
      - run: make build-example-android
      - name: Run e2e test on Android Emulator
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: default
          arch: x86_64
          profile: pixel_7
          avd-name: Pixel 7
          script: make e2e-android

  build-ios:
    runs-on: macos-14
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.USER_NODE_VERSION }}
          cache: 'yarn'
      - name: Install applesimutils
        run: |
          brew tap wix/brew
          brew install applesimutils
      - run: yarn global add react-native-cli
      - run: yarn global add detox-cli
      - run: make dependencies
      - run: make dependencies-example
      - run: make dependencies-example-ios
      - name: List all iPhone Simulator
        run: xcrun simctl list devices available
      - name: Start iOS Simulator
        run: |
          UDID=$(xcrun simctl list devices available --json | jq -r '.devices."com.apple.CoreSimulator.SimRuntime.${{ env.IOS_SIMULATOR_RUNTIME }}"[] | select(.name == "${{ env.IOS_SIMULATOR_DEVICE }}").udid')
          xcrun simctl boot "${UDID}"
      - name: Run e2e test on iOS Simulator
        run: make e2e-ios
        timeout-minutes: 30
