name: Create Release

on:
  push:
    tags:
      - 'v*'

env:
  USER_NODE_VERSION: 12.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.USER_NODE_VERSION }}
      - name: Create release
        run: |
          CURRENT=$(hub release | head -n 1)
          PREV=$(hub release | head -n 2)
          BODY=$(npx lerna-changelog --from=$PREV --to=$CURRENT)
          hub release create -m $CURRENT -m $BODY
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}

