name: Create Release

on:
  push:
    tags:
      - 'v*'

env:
  USER_NODE_VERSION: 12.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.USER_NODE_VERSION }}
      - name: Create release
        run: |
          LATEST_TAG=$(git tag | tail -n 1)
          LATEST_RELEASE=$(hub release | head -n 1)
          BODY=body.txt
          npx lerna-changelog --from=$LATEST_RELEASE --to=$LATEST_TAG > BODY
          hub release create -m $LATEST_TAG -f $BODY $LATEST_TAG
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}

